auth_modules:
  dbx: # Set this to any name you want
    type: userpass
    userpass:
        username: postgres
        password: app_user
    options:
      # options become key=value parameters of the DSN
        sslmode: disable