version: '3.7'

# https://developer.hashicorp.com/consul/tutorials/docker/docker-compose-datacenter
# scp ./* peizhong@10.10.10.1:~/source/repos/codeplay/docker/consul/

services:
  
  consul-server1:
    image: hashicorp/consul:1.16.2
    container_name: consul-server1
    restart: always
    volumes:
     - ./server1.json:/consul/config/server.json:ro
     # - ./certs/:/consul/config/certs/:ro
    networks:
      - consul
    ports:
      # ui
      - "8500:8500"
      - "8600:8600/tcp"
      - "8600:8600/udp"
    command: "agent -bootstrap-expect=3"

  consul-server2:
    image: hashicorp/consul:1.16.2
    container_name: consul-server2
    restart: always
    volumes:
     - ./server2.json:/consul/config/server.json:ro
     # - ./certs/:/consul/config/certs/:ro
    networks:
      - consul
    command: "agent -bootstrap-expect=3"

  consul-server3:
    image: hashicorp/consul:1.16.2
    container_name: consul-server3
    restart: always
    volumes:
     - ./server3.json:/consul/config/server.json:ro
     # - ./certs/:/consul/config/certs/:ro
    networks:
      - consul
    command: "agent -bootstrap-expect=3"

  consul-client1:
    image: hashicorp/consul:1.16.2
    container_name: consul-client1
    restart: always
    volumes:
     - ./client1.json:/consul/config/client.json:ro
     # - ./certs/:/consul/config/certs/:ro
    networks:
      - consul
    ports:
      - "8501:8500"
    command: "agent"

  consul-client2:
    image: hashicorp/consul:1.16.2
    container_name: consul-client2
    restart: always
    volumes:
     - ./client2.json:/consul/config/client.json:ro
     # - ./certs/:/consul/config/certs/:ro
    networks:
      - consul
    ports:
      - "8502:8500"
    command: "agent"

networks:
  consul:
    driver: bridge
