version: '3'

# scp * peizhong@10.10.10.1:~/source/repos/codeplay/docker/prometheus

services:
  node_exporter:
    image: quay.io/prometheus/node-exporter:latest
    container_name: node_exporter
    command:
      - '--path.rootfs=/host'
    pid: host
    restart: unless-stopped
    volumes:
      - '/:/host:ro,rslave'
    
  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    ports:
    - 8080:8080
    volumes:
    - /:/rootfs:ro
    - /var/run:/var/run:rw
    - /sys:/sys:ro
    - /var/lib/docker/:/var/lib/docker:ro
    - /dev/disk/:/dev/disk:ro
  
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: always
    deploy:
      resources:
        limits:
          # cpus: 0.50
          memory: 500m
        reservations:
          # cpus: 0.25
          memory: 256m
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - '--web.enable-lifecycle'
      - '--storage.tsdb.retention=7d'
    ports:
      - 9090:9090

  victoriametrics:
    image: victoriametrics/victoria-metrics
    container_name: victoriametrics
    restart: always
    deploy:
        resources:
            limits:
              # cpus: 0.50
              memory: 500m
            reservations:
              # cpus: 0.25
              memory: 256m
    depends_on:
      - prometheus
    ports:
      - 8428:8428

  grafana:
    image: grafana/grafana-oss:latest
    container_name: grafana
    restart: always
    deploy:
      resources:
        limits:
          # cpus: 0.50
          memory: 258m
        reservations:
          # cpus: 0.25
          memory: 128m
    depends_on:
      - prometheus
      - victoriametrics
    ports:
      - 3000:3000
    volumes:
      - grafana-storage:/var/lib/grafana

volumes:
  grafana-storage: {}